#!/usr/bin/env python3
"""Owner decision 2026-09-29: new CompanyCard prices, printed everywhere at once.

    Pro       $5.99 a month billed monthly, $4.99 a month billed yearly ($59.88 a year)
    Business  $4.99 per user a month billed monthly, $3.99 billed yearly, no seat minimum
    Free / Enterprise unchanged

Why Business is $3.99: the pricing rule was "$5.99 billed yearly, unless a
competitor's comparable per-user team plan is below $5.99 on yearly billing;
then that competitor's price minus $1, rounded to .99, floor $3.99; monthly =
yearly + $1". Competitor team rates read on 2026-09-29 (research in the CEO
workspace, from each vendor's own page): Blinq Business $4.99 billed annually,
HiHello Business $5 billed yearly, Wave Connect Teams $5 billed yearly. All
are below $5.99; $4.99 - $1 = $3.99 (= the floor). Monthly = $4.99.

What this changes. The one-voice facts (seo/facts.py) are regenerated by
seo/add_verified_facts.py and seo/build_llms_full.py; the small-business blocks
by seo/geo_small_business_answer_2026_09_29.py. Everything else that quotes
OUR price is hand-written copy, rewritten here with exact (old, new) pairs:

- GENERIC pairs: the same price phrase in many pages (e.g. "Pro $7.99/mo, or
  $5.99/mo billed yearly"). Each names Pro or Business next to the figure, so
  a competitor's $7.99 (Popl Pro) or $12 (Calendly Standard) is never touched.
- PAGE pairs: comparison sentences whose CONCLUSION flips with the new price
  ("our Business plan is the most expensive team plan", "half our $12").
  Each is rewritten with the competitor figures already on the page plus the
  2026-09-29 research. Wave Connect's figures are corrected at the same time:
  its pricing page opens on yearly billing (aria-checked="true" on "Toggle
  yearly billing"), so the "$7 Pro / $5 Teams" our pages called monthly are
  its yearly rates; switched to monthly they are $9 and $7 per user.

The pairs are applied to the published files only (root *.html, llms.txt,
app/mobile.html). The seo/pages_data*.py sources are NOT edited: as recorded
in seo/remove_billing_preview_note_2026_09_29.py, their build_pages*.py
renderers drop the GA4 tag and the FRESH block and are no longer run, and
several of them already carry older prices ($8 Pro) than the pages they once
printed. The published HTML is the source of truth for those pages; never
re-render them from pages_data*.py without re-reading the prices first.
JSON-LD FAQ answers are rewritten too, and seo/sync_faq_schema.py then proves
they byte-match the visible answers. pricing.html's OFFERS JSON-LD is updated
from the constants below.

Idempotent: every old string disappears once replaced, so a re-run is a no-op.
New text is written with «TOKENS» first and expanded at the end, so a pair can
never match text another pair has just written.

Run from repo root, in this order:
  python3 seo/reprice_2026_09_29.py
  python3 seo/geo_small_business_answer_2026_09_29.py
  python3 seo/add_verified_facts.py
  python3 seo/sync_faq_schema.py      # must exit 0
  python3 seo/build_llms_full.py
"""
import glob, json, re, sys

DATE = "2026-09-29"
PRO_M, PRO_Y, PRO_YEAR = "5.99", "4.99", "59.88"
BIZ_M, BIZ_Y = "4.99", "3.99"
TOK = {"«PM»": "$" + PRO_M, "«PY»": "$" + PRO_Y, "«PT»": "$" + PRO_YEAR,
       "«BM»": "$" + BIZ_M, "«BY»": "$" + BIZ_Y}

# ---------------------------------------------------------------------------
# PAGE pairs first (they contain the generic phrases, so they must win).
# ---------------------------------------------------------------------------
PAGE = [
    # ---------------- blinq-vs-popl ----------------
    ("No seat minimum: one user is $12/mo, two are $24/mo",
     "No seat minimum: one user is «BM»/mo, two are $9.98/mo"),
    ("Blinq Business is $6.99 per user against our $12, and at five people or more it is simply cheaper. ",
     ""),
    ("they are worth the two dollars over cheaper single-card plans, ours included.",
     "they are worth the extra over cheaper single-card plans, ours included."),
    ("We have no seat minimum, where Blinq Business starts at five cards — which matters for a business of one or two "
     "that wants the team plan ($12 or $24 against $34.95) and stops mattering at three ($36 against $34.95). And our "
     "Pro plan is $7.99 a month against Blinq Premium at $9.99, for a plainer card without the sales tooling.",
     "We have no seat minimum, where Blinq Business starts at five cards — so one or two people can buy the team plan "
     "(«BM» or $9.98 a month, against Blinq's five-card floor of $34.95) — and our per-user rate is the lower one at any "
     "size: «BM» against $6.99 billed monthly, «BY» against $4.99 billed yearly. And our Pro plan is «PM» a month against "
     "Blinq Premium at $9.99, for a plainer card without the sales tooling."),
    ("and on the per-seat team rate ($6.99 against our $12), and it loses to Popl on event lead capture outright. What it "
     "has against this pair is narrow and checkable: we publish a price where Popl publishes none; we have no seat minimum "
     "where Blinq Business starts at five cards, which only matters for a team of one or two; and our Pro plan is $7.99 a "
     "month against Blinq Premium at $9.99,",
     "and it loses to Popl on event lead capture outright. What it has against this pair is checkable: we publish a price "
     "where Popl publishes none; we have no seat minimum where Blinq Business starts at five cards, and our per-user team "
     "rate is lower («BM» against $6.99 billed monthly, «BY» against $4.99 billed yearly); and our Pro plan is «PM» a "
     "month against Blinq Premium at $9.99,"),

    # ---------------- hihello-vs-blinq ----------------
    ("Pro $7.99/mo, or $5.99/mo billed yearly — <b>within a cent of HiHello on either term, for one card instead of sixteen</b>",
     "Pro «PM»/mo, or «PY»/mo billed yearly — <b>about $2 a month below HiHello billed monthly and $1 below billed yearly, "
     "for one card instead of sixteen</b>"),
    ("Business $12/user/mo, or $10/user/mo annually — <b>the most expensive of the three</b>",
     "Business «BM»/user/mo, or «BY»/user/mo annually — <b>the lowest per-user rate of the three</b>"),
    ("CompanyCard figures from our own pricing page, re-read 13 September 2026. We are the publisher of this page and the "
     "comparison is stated plainly rather than framed to flatter us: HiHello and Blinq are both cheaper than CompanyCard on "
     "the team tier, HiHello Professional is within a cent of CompanyCard Pro on either billing term while including "
     "sixteen cards to our one, and both give a bigger free plan.",
     "CompanyCard figures from our own pricing page, re-read 29 September 2026. We are the publisher of this page and the "
     "comparison is stated plainly rather than framed to flatter us: CompanyCard has the lowest per-user team rate of the "
     "three and a lower Pro price than HiHello Professional, but HiHello Professional includes sixteen cards to our one, "
     "and both give a bigger free plan."),
    ("There is exactly one axis on this page where CompanyCard is not simply the more expensive option, and it is the seat floor.",
     "CompanyCard has the lowest published per-user rate on this page, but the thing we do differently is the seat floor."),
    ("Our per-user rate is $12 a month, double HiHello's $6 billed monthly — so two people on CompanyCard Business pay $24 "
     "a month against a five-user HiHello Business floor of $30 billed monthly, or $20 against $25 if both are billed "
     "yearly. The advantage is real but it is narrow, and it disappears entirely the moment you have five people.",
     "Our per-user rate is «BM» a month billed monthly, against HiHello's $6 — so two people on CompanyCard Business pay "
     "$9.98 a month against a five-user HiHello Business floor of $30 billed monthly, or $7.98 against $25 if both are "
     "billed yearly. At five people the gap is the per-user rate alone: $24.95 against $30 billed monthly, $19.95 against "
     "$25 billed yearly."),
    ("CompanyCard is more expensive than both and has a smaller free plan: 1 card carrying a small CompanyCard credit "
     "against HiHello's 4 and Blinq's 2, Pro at $7.99 a month against HiHello's $8 billed monthly ($6 yearly) for one card "
     "instead of sixteen, and Business at $12 per user against HiHello's $6 ($5 yearly) and Blinq's $6.99. The one axis "
     "where CompanyCard differs is the seat floor",
     "CompanyCard is cheaper than both on published rates but has a smaller free plan: 1 card carrying a small "
     "CompanyCard credit against HiHello's 4 and Blinq's 2; Pro at «PM» a month («PY» yearly) against HiHello's $8 billed "
     "monthly ($6 yearly), for one card instead of sixteen; and Business at «BM» per user («BY» yearly) against HiHello's "
     "$6 ($5 yearly) and Blinq's $6.99 ($4.99 yearly). The other axis where CompanyCard differs is the seat floor"),

    # ---------------- hihello-vs-popl ----------------
    ("CompanyCard Business starts at one seat, $12 a month each,",
     "CompanyCard Business starts at one seat, «BM» a month each («BY» billed yearly),"),
    ("<b>Five people or more.</b> HiHello Business at $6 per user billed monthly, or $5 yearly, is half our $12 and it is "
     "self-serve. From five up, HiHello is the better-priced card platform of the three and we say so.",
     "<b>Five people or more.</b> HiHello Business is $6 per user billed monthly, or $5 yearly, and it is self-serve. "
     "CompanyCard Business is «BM» per user billed monthly, or «BY» yearly, so on published rates it is the lower price "
     "at five and above — but you set it up by talking to us, where HiHello you can buy online."),
    ("3 × Business = <b>$36/mo</b> · $30/mo billed yearly",
     "3 × Business = <b>$14.97/mo</b> · $11.97/mo billed yearly"),
    ("<td><b>$60/mo</b> · $50/mo billed yearly</td>",
     "<td><b>$24.95/mo</b> · $19.95/mo billed yearly</td>"),
    ("<td><b>$300/mo</b> · $250/mo billed yearly</td>",
     "<td><b>$124.75/mo</b> · $99.75/mo billed yearly</td>"),
    ("<b>You are five or more:</b> HiHello Business, $6 a user billed monthly, is half our rate and self-serve. Buy it.",
     "<b>You are five or more and want to buy online today:</b> HiHello Business, $6 a user billed monthly, is "
     "self-serve. CompanyCard Business is «BM» a user billed monthly, but you set it up by talking to us."),
    ("so three people are $36 a month billed monthly or $30 billed yearly, with the admin dashboard and brand lock "
     "included. Three users is the one headcount where our published team rate is competitive; at five HiHello is cheaper.",
     "so three people are $14.97 a month billed monthly or $11.97 billed yearly, with the admin dashboard and brand lock "
     "included. Our published per-user rate is also below HiHello's at five and above; HiHello's advantage there is that "
     "it is self-serve."),

    # ---------------- digital-business-card-cost ----------------
    ("The prices below were read off each vendor's own pricing page on 1 September 2026.</p>",
     "The prices below were read off each vendor's own pricing page on 1 September 2026; CompanyCard's own prices and "
     "Wave Connect's billing periods were re-read on 29 September 2026.</p>"),
    ("CompanyCard's Business plan is $12 per user and is the most expensive team plan on this page — that is stated here "
     "rather than left out.",
     "CompanyCard's Business plan is «BM» per user billed monthly, or «BY» billed yearly, with no seat minimum."),
    ("<td>Pro $7/mo</td><td>Teams $5 per user/mo</td>",
     "<td>Pro $9/mo, or $7/mo billed yearly</td><td>Teams $7 per user/mo, or $5 billed yearly</td>"),
    ("<b>Mobilo's Pro plan is less than half our Pro price</b> — $3 against $7.99. <b>Our Business plan is the most "
     "expensive team plan on this page</b>, at roughly twice HiHello's or Wave Connect's per-user rate.",
     "<b>Mobilo's Pro plan is cheaper than our Pro</b> — $3 against «PM» billed monthly, or «PY» billed yearly. "
     "<b>Our Business plan is the lowest published per-user team rate on this page</b> — «BM» billed monthly and «BY» "
     "billed yearly — but it is set up by talking to us rather than bought online."),
    ("The cheapest paid personal plan on this page is Mobilo Pro at $3 a month, which is less than half what CompanyCard "
     "charges for Pro.",
     "The cheapest paid personal plan on this page is Mobilo Pro at $3 a month, below CompanyCard Pro at «PM» a month "
     "(«PY» billed yearly)."),
    ("For teams, Mobilo's Teams plan at $4 a month billed annually and Wave Connect's $5 per user a month and HiHello's $5 "
     "per user a month billed yearly ($6 monthly) are the lowest published rates.",
     "For teams, CompanyCard's Business plan at «BY» per user a month billed yearly («BM» monthly) and Mobilo's Teams plan "
     "at $4 a month billed annually are the lowest published rates, followed by Wave Connect's and HiHello's $5 per user a "
     "month billed yearly ($7 and $6 monthly)."),
    ("Between about $4 and $12 per person a month, but check the minimum before the rate.",
     "Between about $4 and $7 per person a month, but check the minimum before the rate."),
    ("CompanyCard's Business plan is $12 per user a month with no seat minimum, which is the most expensive per-user rate "
     "here and the only one a two-person team can buy at face value.",
     "CompanyCard's Business plan is «BM» per user a month, or «BY» billed yearly, with no seat minimum, which makes it "
     "the lowest per-user rate here and the only one a two-person team can buy at face value."),

    # ---------------- mobilo-alternative ----------------
    ("An honest comparison — Mobilo&#x27;s paid plans are cheaper, and we say so.",
     "An honest comparison — Mobilo&#x27;s Pro plan is cheaper than ours, and we say so."),
    ("and its paid plans are cheaper than ours — Pro at $3 a month, and Teams at $4 and Business at $5 a month billed "
     "annually, as of 1 September 2026, against our $5.99 Pro and $10 per user Business billed annually ($7.99 and $12 "
     "monthly). If price is the deciding factor, that is your answer and you should take it.",
     "and its Pro plan is cheaper than ours — $3 a month as of 1 September 2026, against our «PY» billed annually or «PM» "
     "monthly. On team plans it is close: Mobilo lists Teams at $4 and Business at $5 a month billed annually, against our "
     "«BY» per user Business billed annually («BM» monthly). If one person's price is the deciding factor, Mobilo is your "
     "answer and you should take it."),
    ("<p>No, and we would rather say so. As of 1 September 2026 Mobilo lists Pro at $3 a month, with Teams at $4 and "
     "Business at $5 a month billed annually — against CompanyCard's $5.99 Pro and $10 per user Business billed annually "
     "($7.99 and $12 billed monthly). Whichever way you bill it, Mobilo wins on price.",
     "<p>Not for one person, and we would rather say so. As of 1 September 2026 Mobilo lists Pro at $3 a month, with "
     "Teams at $4 and Business at $5 a month billed annually — against CompanyCard's «PY» Pro and «BY» per user Business "
     "billed annually («PM» and «BM» billed monthly). Mobilo wins on the individual plan; on the team plans the published "
     "annual rates are within about a dollar of each other."),

    # ---------------- popl-vs-uniqode ----------------
    ("<b>Uniqode wins on price and on breadth.</b> $6 per user per month is half our Business rate, and if you already "
     "run QR codes",
     "<b>Uniqode wins on breadth.</b> If you already run QR codes"),
    ("<b>Where we lose.</b> On the headline team number Uniqode is cheaper: $6 per user per month against our $12 Business "
     "plan. If you have five people, are happy to pay for a year, and want the lowest published rate, Uniqode is the "
     "better buy and this page is not going to argue otherwise.",
     "<b>Where we lose.</b> Uniqode is the broader QR platform, and its Team plan ($6 per user per month, billed yearly) "
     "is bought online. Our Business rate is lower («BM» per user a month, or «BY» billed yearly), but if you want the "
     "cards in the same account as your other QR codes, Uniqode is the better buy and this page is not going to argue "
     "otherwise."),
    ("It loses on the headline team price: Uniqode's Team plan is $6 per user per month against our $12 Business, so for a "
     "team that is happy to pay annually Uniqode is cheaper and we will not pretend otherwise. What we have against this "
     "pair is narrow and checkable — we bill monthly",
     "It loses on breadth: Uniqode covers QR uses well beyond business cards, and its $6 per user Team plan is bought "
     "online where our Business plan is set up by talking to us. What we have against this pair is checkable — our "
     "Business rate is lower («BM» per user a month, or «BY» billed yearly), we bill monthly"),

    # ---------------- uniqode-alternative ----------------
    ("<p>Not on the headline number for a team: Uniqode's Team plan is $6 per user per month against our $12 Business, "
     "though theirs is annual-only and ours is not. For a single person our Pro is $7.99 a month, or $5.99 a month billed "
     "yearly. Which is cheaper depends entirely on whether you want to commit for a year — compare on your own headcount "
     "and billing preference.</p>",
     "<p>On the published rates, yes: Uniqode's Team plan is $6 per user per month and annual-only, against our Business "
     "at «BM» per user a month, or «BY» billed yearly. For a single person our Pro is «PM» a month, or «PY» a month billed "
     "yearly. Uniqode's advantages are elsewhere — a broader QR platform and a team plan you can buy online — so compare "
     "on what you need, not only the rate.</p>"),
    ("On the headline team price Uniqode at $6/user/mo is cheaper than CompanyCard's $12 Business and the page says so; "
     "CompanyCard's checkable edges against this pair are monthly billing,",
     "CompanyCard's Business rate («BM»/user/mo, or «BY» billed yearly) is below Uniqode's $6/user/mo, while Uniqode is "
     "the broader QR platform and sells its team plan online; CompanyCard's other checkable edges against this pair are "
     "monthly billing,"),

    # ---------------- wave-connect-alternative ----------------
    ("Wave&#x27;s free tier and paid prices beat ours on several counts. The one place CompanyCard wins is the team seat floor.",
     "Wave&#x27;s free tier does more than ours; CompanyCard is lower on price and has no team seat floor."),
    ("<p class=\"lead\">We'll save you the sales pitch: on published prices and free-tier features, Wave Connect beats us "
     "in several places. There is one specific case where CompanyCard is the better buy, and this page is mostly about "
     "telling you which one you're in.</p>",
     "<p class=\"lead\">We'll save you the sales pitch: on free-tier features Wave Connect beats us; on published prices "
     "and the team seat floor CompanyCard does. This page is mostly about telling you which case you're in.</p>"),
    ("here is the part those pages usually leave out: on the published monthly prices as of September 2026, Wave Connect "
     "is cheaper than CompanyCard and its free tier does more.",
     "here is the part those pages usually leave out: Wave Connect's free tier does more than ours."),
    ("Its Pro is $7 a month to our $7.99 and its Teams plan is $5 per user to our $12 — monthly prices on both sides; "
     "billed annually ours are $5.99 and $10 per user, and Wave's yearly rates sit behind a toggle on its pricing page. "
     "Those are real differences and we are not going to explain them away.",
     "Those are real differences and we are not going to explain them away.</p><p>On price it runs the other way. Wave's "
     "pricing page opens on yearly billing, where Pro is $7 a month and Teams $5 per user; switched to monthly they are $9 "
     "and $7 per user (read 29 September 2026). Ours are «PY» and «BY» per user billed yearly, or «PM» and «BM» billed "
     "monthly."),
    ("There is one published place we win, and it is narrow but decisive for the people it affects:",
     "There is one more published place we win, and it is decisive for the people it affects:"),
    ("<td>$7/mo Pro (billed monthly)</td>", "<td>$9/mo Pro ($7/mo billed yearly)</td>"),
    ("<td>$5/user/mo (billed monthly)</td>", "<td>$7/user/mo ($5 billed yearly)</td>"),
    ("in September 2026. Wave wins most of these columns. Terms change — check before deciding.",
     "on 29 September 2026; the page opens on yearly billing, and the monthly figures are shown with the switch off. Wave "
     "wins the free-plan columns; CompanyCard wins on price and the seat minimum. Terms change — check before deciding."),
    ("<h3>A team of three or more, price-led</h3><p>Wave, on the published per-user numbers. Run the total for your actual "
     "headcount.</p>",
     "<h3>A team of three or more, price-led</h3><p>CompanyCard, on the published per-user numbers: «BM» against $7 billed "
     "monthly, «BY» against $5 billed yearly. Wave Teams is bought online; ours is set up by talking to us.</p>"),
    ("and its paid plans are cheaper on the published monthly prices — $7 a month against our $7.99, and $5 per user "
     "against our $12 (billed annually, ours are $5.99 and $10 per user; Wave's yearly prices sit behind a toggle on its "
     "site). The one published place CompanyCard wins is the team floor: Wave's Teams plan requires three seats, and we "
     "have no seat minimum.",
     "while our free plan has no lead capture. On price CompanyCard is lower: as of 29 September 2026 Wave lists Pro at $9 a month billed "
     "monthly ($7 billed yearly) and Teams at $7 per user ($5 billed yearly), against our «PM» and «BM» per user («PY» and "
     "«BY» billed yearly). CompanyCard also has no seat minimum, where Wave's Teams plan requires three seats."),
    ("<p>If you are a single user who wants lead capture on a free plan, or price is your deciding factor at any team size "
     "of three or more. On the published numbers those are Wave's,",
     "<p>If you are a single user who wants lead capture on a free plan, or you want a team plan you can buy online "
     "without talking to anyone. Those are Wave's,"),
    ("Wave Connect alternative (Wave's free tier and prices beat ours on several counts; our edge is no 3-seat team floor)",
     "Wave Connect alternative (Wave's free tier does more than ours; our edges are lower published prices and no 3-seat "
     "team floor)"),

    # ---------------- free-digital-business-card-comparison ----------------
    ("If price is what matters, Mobilo's paid plans are cheaper than ours.",
     "If the lowest individual price is what matters, Mobilo's Pro is cheaper than ours."),
    ("<td>None</td><td>$7.99/mo Pro</td></tr>",
     "<td>None</td><td>«PY»/mo Pro billed yearly («PM»/mo billed monthly)</td></tr>"),
    ("<td>3 seats (Teams)</td><td>$7/mo Pro</td></tr>",
     "<td>3 seats (Teams)</td><td>$7/mo Pro billed yearly ($9/mo billed monthly)</td></tr>"),
    ("Mobilo's Pro at $3 a month is cheaper than our $7.99, and we are not going to pretend otherwise.",
     "Mobilo's Pro at $3 a month is cheaper than our «PM» («PY» billed yearly), and we are not going to pretend otherwise."),
    ("Wave Connect's Pro is $7 a month.", "Wave Connect's Pro is $9 a month billed monthly, or $7 billed yearly."),

    # ---------------- best-* ----------------
    ("Mobilo lists Pro at $3/mo — cheaper than our $5.99/mo annual or $7.99 monthly",
     "Mobilo lists Pro at $3/mo — cheaper than our «PY»/mo annual or «PM» monthly"),
    ("<td>$7 Pro · $5 per user Teams</td>", "<td>$9 Pro · $7 per user Teams ($7 · $5 billed yearly)</td>"),

    # ---------------- the retired "Save up to 25%" tag, quoted in two lp-notes ----------------
    ("CompanyCard figures are our own published rates on our <a href=\"pricing.html\">pricing page</a>, where annual "
     "billing is labelled “Save up to 25%”.</p>",
     "CompanyCard figures are our own published rates on our <a href=\"pricing.html\">pricing page</a>, re-read 29 "
     "September 2026.</p>"),

    # ---------------- llms.txt competitor lines ----------------
    ("CompanyCard loses to HiHello on the free plan (4 cards, no credit vs our 1 with a credit) and on the per-seat team "
     "rate ($6 monthly / $5 yearly vs our $12 / $10); HiHello Professional and CompanyCard Pro are within a cent of each "
     "other on either billing term ($8 vs $7.99 monthly, $6 vs $5.99 yearly) and HiHello's includes sixteen cards",
     "CompanyCard loses to HiHello on the free plan (4 cards, no credit vs our 1 with a credit) and on self-serve team "
     "checkout; CompanyCard's published rates are lower — team $6 monthly / $5 yearly vs our «BM» / «BY» per user, and "
     "Professional $8 vs our Pro «PM» monthly, $6 vs «PY» yearly — though HiHello's includes sixteen cards"),
    ("CompanyCard loses to Blinq on the free plan (2 cards, no credit vs our 1 with a credit) and on the per-seat team rate "
     "($6.99 vs our $12)",
     "CompanyCard loses to Blinq on the free plan (2 cards, no credit vs our 1 with a credit); its per-seat team rate is "
     "lower («BM» vs $6.99 monthly, «BY» vs $4.99 yearly)"),
    ("and Pro at $7.99 vs Blinq Premium at $9.99", "and Pro at «PM» vs Blinq Premium at $9.99"),
    ("Mobilo alternative (Mobilo is NFC-hardware-centric; its paid plans are cheaper than ours)",
     "Mobilo alternative (Mobilo is NFC-hardware-centric; its Pro plan is cheaper than ours)"),
]

# ---------------------------------------------------------------------------
# GENERIC pairs: our own price phrases. Longest first.
# ---------------------------------------------------------------------------
GENERIC = [
    ("$7.99 a month, or $5.99 a month billed yearly ($71.88 a year)", "«PM» a month, or «PY» a month billed yearly («PT» a year)"),
    ("$7.99/month billed monthly, or $5.99/month billed annually ($71.88/year)", "«PM»/month billed monthly, or «PY»/month billed annually («PT»/year)"),
    ("<b>$7.99/mo</b> · $5.99/mo billed yearly ($71.88/yr)", "<b>«PM»/mo</b> · «PY»/mo billed yearly («PT»/yr)"),
    ("Pro is $5.99 a month billed yearly ($71.88 a year) or $7.99 billed monthly", "Pro is «PY» a month billed yearly («PT» a year) or «PM» billed monthly"),
    ("Pro is $5.99 a month billed yearly ($71.88 a year), or $7.99 billed monthly", "Pro is «PY» a month billed yearly («PT» a year), or «PM» billed monthly"),
    ("$7.99 per month Pro plan is for ($5.99 per month billed annually)", "«PM» per month Pro plan is for («PY» per month billed annually)"),
    ("$7.99 a month, or $5.99 a month billed yearly", "«PM» a month, or «PY» a month billed yearly"),
    ("$7.99 a month, or $5.99 a month billed annually", "«PM» a month, or «PY» a month billed annually"),
    ("$7.99 per month (or $5.99 a month billed yearly)", "«PM» per month (or «PY» a month billed yearly)"),
    ("$7.99/month or $5.99/month billed yearly", "«PM»/month or «PY»/month billed yearly"),
    ("$7.99/month for Pro ($5.99/month billed annually)", "«PM»/month for Pro («PY»/month billed annually)"),
    ("Pro published at $7.99/mo ($5.99 annual)", "Pro published at «PM»/mo («PY» annual)"),
    ("$7.99 a month for Pro ($5.99 billed yearly)", "«PM» a month for Pro («PY» billed yearly)"),
    ("$7.99 for Pro ($5.99/mo billed yearly)", "«PM» for Pro («PY»/mo billed yearly)"),
    ("Pro is $7.99 a month or $5.99 billed yearly", "Pro is «PM» a month or «PY» billed yearly"),
    ("$7.99 Pro ($5.99/mo billed yearly)", "«PM» Pro («PY»/mo billed yearly)"),
    ("Pro $7.99/mo ($5.99/mo annual)", "Pro «PM»/mo («PY»/mo annual)"),
    ("Pro $7.99/mo, or $5.99/mo billed annually", "Pro «PM»/mo, or «PY»/mo billed annually"),
    ("Pro $7.99/mo, or $5.99/mo billed yearly", "Pro «PM»/mo, or «PY»/mo billed yearly"),
    ("$7.99/mo Pro ($5.99/mo billed annually)", "«PM»/mo Pro («PY»/mo billed annually)"),
    ("$7.99/mo Pro · $12/user/mo Business", "«PM»/mo Pro · «BM»/user/mo Business"),
    ("Pro $7.99/mo, Business $12/user/mo", "Pro «PM»/mo, Business «BM»/user/mo"),
    ("$7.99 Pro, $12 per user Business", "«PM» Pro, «BM» per user Business"),
    ("$7.99 a month if you want custom branding", "«PM» a month if you want custom branding"),
    ("Pro at $7.99 a month, or", "Pro at «PM» a month, or"),
    # Business
    ("$12 per user a month, or $10 per user a month billed yearly", "«BM» per user a month, or «BY» per user a month billed yearly"),
    ("$12 per user a month, or $10 per user a month billed annually", "«BM» per user a month, or «BY» per user a month billed annually"),
    ("$12 per user Business ($10 billed yearly)", "«BM» per user Business («BY» billed yearly)"),
    ("Business $12/user/mo ($10 annual)", "Business «BM»/user/mo («BY» annual)"),
    ("Business $12/user/mo, or $10/user/mo billed annually", "Business «BM»/user/mo, or «BY»/user/mo billed annually"),
    ("$12/user/month billed monthly, or $10/user/month billed annually", "«BM»/user/month billed monthly, or «BY»/user/month billed annually"),
    ("$12/user/mo ($10 billed annually)", "«BM»/user/mo («BY» billed annually)"),
    ("Business $12 per user/month", "Business «BM» per user/month"),
    ("Business at $12 per user a month", "Business at «BM» per user a month"),
    ("Business is $12 per user a month", "Business is «BM» per user a month"),
    ("at $12 per user a month with no seat minimum", "at «BM» per user a month with no seat minimum"),
    ("$12 per user a month for Business", "«BM» per user a month for Business"),
    ("Business is $12 per user per month", "Business is «BM» per user per month"),
    ("Our team plan is $12 per user per month", "Our team plan is «BM» per user per month"),
    ("$12 per user for Business", "«BM» per user for Business"),
    ("$12 per user for a team", "«BM» per user for a team"),
    ("$12 per user Business", "«BM» per user Business"),
    # app
    ("Upgrade — from $5.99/mo", "Upgrade — from «PY»/mo"),
]

PAIRS = PAGE + GENERIC


def expand(s):
    for k, v in TOK.items():
        s = s.replace(k, v)
    return s


def apply(text, hits):
    for i, (old, new) in enumerate(PAIRS):
        n = text.count(old)
        if n:
            hits[i] = hits.get(i, 0) + n
            text = text.replace(old, new)
    return expand(text)


def offers_jsonld(h):
    """pricing.html OFFERS block: rewrite the Pro/Business offers from the constants."""
    m = re.search(r'(<!-- OFFERS:BEGIN -->\n<script type="application/ld\+json">)(.*?)(</script>)', h, re.S)
    assert m, "pricing.html: no OFFERS block"
    d = json.loads(m.group(2))
    agg = d["offers"]
    agg["highPrice"] = PRO_M  # Pro monthly is now the highest listed price
    out = []
    for o in agg["offers"]:
        n = o["name"]
        if n == "Pro":
            o["price"] = PRO_M; o["priceSpecification"]["price"] = PRO_M
        elif n == "Pro (annual)":
            o["price"] = PRO_Y; o["priceSpecification"]["price"] = PRO_Y
            o["description"] = f"Pro billed annually — ${PRO_YEAR} per year."
        elif n == "Business":
            o["price"] = BIZ_M; o["priceSpecification"]["price"] = BIZ_M
        out.append(o)
        if n == "Business" and not any(x["name"] == "Business (annual)" for x in agg["offers"]):
            out.append({"@type": "Offer", "name": "Business (annual)", "price": BIZ_Y, "priceCurrency": "USD",
                        "description": "Business billed annually, per user per month, with no seat minimum.",
                        "url": o["url"], "availability": o["availability"],
                        "priceSpecification": {"@type": "UnitPriceSpecification", "price": BIZ_Y,
                                               "priceCurrency": "USD", "billingIncrement": 12,
                                               "unitText": "user per month"}})
    agg["offers"] = out
    agg["offerCount"] = len(out)
    body = json.dumps(d, ensure_ascii=False)
    return h[:m.start(2)] + body + h[m.end(2):]


def pricing_cards(h):
    h = h.replace('<span data-monthly="7.99" data-annual="5.99">7.99</span>',
                  f'<span data-monthly="{PRO_M}" data-annual="{PRO_Y}">{PRO_M}</span>')
    h = h.replace('<span data-monthly="12" data-annual="10">12</span>',
                  f'<span data-monthly="{BIZ_M}" data-annual="{BIZ_Y}">{BIZ_M}</span>')
    # "Save up to 25%" is no longer true (Pro saves 16%, Business 20%) and the
    # owner asked for automatic-discount wording to go: the toggle stays, the tag goes.
    h = h.replace('\n      <span class="save-tag">Save up to 25%</span>', "")
    return h


def bump_fresh(h):
    m = re.search(r"<!-- FRESH:BEGIN -->.*?<!-- FRESH:END -->", h, re.S)
    if not m:
        return h
    fresh = re.sub(r'"dateModified":"\d{4}-\d{2}-\d{2}"', f'"dateModified":"{DATE}"', m.group(0))
    return h[:m.start()] + fresh + h[m.end():]


def main():
    hits = {}
    pages = sorted(glob.glob("*.html"))
    others = ["llms.txt", "app/mobile.html"]
    sources = []  # see the docstring: pages_data*.py renderers are retired
    changed_pages = []
    for f in pages + others + sources:
        s = open(f, encoding="utf-8").read()
        t = apply(s, hits)
        if f == "pricing.html":
            t = offers_jsonld(pricing_cards(t))
        if t != s:
            if f.endswith(".html") and "/" not in f:
                t = bump_fresh(t)
                changed_pages.append(f)
            open(f, "w", encoding="utf-8").write(t)
            print("  updated", f)
    sm = open("sitemap.xml", encoding="utf-8").read(); orig = sm
    for f in changed_pages:
        loc = "https://company-card.com/" + ("" if f == "index.html" else f)
        sm = re.sub(rf"(<loc>{re.escape(loc)}</loc><lastmod>)\d{{4}}-\d{{2}}-\d{{2}}", rf"\g<1>{DATE}", sm)
    if sm != orig:
        open("sitemap.xml", "w", encoding="utf-8").write(sm); print("  updated sitemap.xml")
    # Every page pair must have landed: its new text is on some published file
    # now (a pair whose new text is empty only deletes, so it is checked by
    # the old text being gone). Holds on the first run and on every re-run.
    corpus = "".join(open(f, encoding="utf-8").read() for f in pages + others)
    missing = [o for o, n in PAGE if (expand(n) not in corpus if n else o in corpus)]
    for o in missing:
        print("  PAGE PAIR NOT IN PLACE:", o[:110], file=sys.stderr)
    if missing:
        sys.exit(1)
    print(f"pairs applied: {sum(hits.values())} replacements across {len(hits)} distinct pairs")


if __name__ == "__main__":
    main()
